name: CI Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20 with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Yarn (v4) via Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.x --activate

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/patches
            .pnp.*
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with Yarn 4
        run: yarn install --immutable

      - name: Run all checks in parallel
        run: |
          yarn all:lint &                   
          yarn format:check &              
          yarn all:build &                 
          yarn all:test --exclude=tasks-ui &
          wait
